import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex w-full flex-col gap-0 bg-stone-50 sm:gap-36">
                <div className="flex flex-col">
                    <Header />
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
